### ISSUE TITLE
Possible parsing bug? ('%EOF% expected')

### ISSUE THREAD

**Issue by Unknown6656** [Dervall/Piglet#55]
I am writing a simple parser for number sequences and written English numbers, e.g. `"one-hundred-and-twenty-five" --> 125`.

The grammar for number sequences should look as follows:
```
digit := "zero"
       |  ...
       | "nine"

sequence := digit
          | digit "-" sequence
```
My code looks as follows:
```csharp
private static readonly Dictionary<decimal, string> TrivialDigitRegex = new Dictionary<decimal, string>
{
    [0] = "zero",
    [1] = "one",
    [2] = "two",
    [3] = "three",
    [4] = "four",
    [5] = "five",
    [6] = "six",
    [7] = "seven",
    [8] = "eight",
    [9] = "nine",
};


IParserConfigurator<decimal> conf = ParserFactory.Configure<decimal>();
INonTerminal<decimal> digit = conf.CreateNonTerminal();
            
foreach (var elem in from kvp in TrivialDigitRegex
                     select conf.CreateTerminal(kvp.Value, s => kvp.Key))
    digit.AddProduction(elem).SetReduceToFirst();

ITerminal<decimal> seperator = conf.CreateTerminal("-");
INonTerminal<decimal> sequence = conf.CreateNonTerminal();

sequence.AddProduction(digit, seperator, sequence).SetReduceFunction(a => a[0] * 10 + a[2]);
sequence.AddProduction(digit).SetReduceToFirst();
            
var parser = conf.CreateParser();
var result = parser.Parse("three-one-five");
```
It fails, however, on the last line with the following exception:

> Piglet.Parser.ParseException occurred
  HResult=0x80131500
  Message=Illegal token -. Expected %EOF%
  Source=Piglet
  StackTrace:
   at Piglet.Parser.LRParser`1.Parse(ILexerInstance`1 lexerInstance) in ....../LRParser.cs:line 90
   at Piglet.Parser.LRParser`1.Parse(String input) in ....../LRParser.cs:line 158

It shall be noted that the execution of the following line works flawlessly:
```csharp
var result = parser.Parse("three"); // returns 3
```
Is it a possible parsing bug or am I missing something important? As far as I can see my grammar definition should be correct (leaving aside the fact, that the grammar's 'entry point' should be `sequence` and not `digit`, but I have not been able to find out how to set the parser's start symbol without reflection).

**Comment by Dervall** [comment]
You're right that it's correct, however the starting symbol is wrong. Piglet by default uses the first non-terminal you create to be the starting symbol. So if you create the nonterminal for `sequence` before you create the `digit` nonterminal things should work as expected.

Let me know how that turns out for you!

There is a method for settings the start symbol on the parser configurator but for some reason I didn't expose that into the interface. I can't really see why I did it that way, and I really don't remember :) As far as I can see there should be no ill effects to exposing that and allowing the user to create nonterminals in whatever order and set the start point later. Feel free to add that if you so desire.

**Comment by Unknown6656** [comment]
Thank you very much for your help. I was not aware that the order of `Create{Terminal|NonTerminal}` mattered. I thought that these methods were (more or less) sideeffect-free. I will be more cautious in the future.

I will maybe expose the method to set the start symbol in my GitHub fork.
Thanks.
